### ISSUE TITLE
Is maxCol working?

### ISSUE THREAD

**Issue by tanelkarp** [kudago/waterfall#19]
Hi @dfcreative,
waterfall is an awesome lightweight plugin, thank you for the awesome job! I'm wondering if the maxCol option is supposed to work or not? I tried setting it via data attribute, as well through the JS init, but the script seems to ignore it.

```javascript
$( '#newsgrid' ).waterfall({
  colMinWidth: 300,
  maxCols: 2,
  autoresize: true
});
```

**Comment by dfcreative** [comment]
Hi! As usually happens with verbal promises, they didn’t happen. Sorry about that. dup #23
