### ISSUE TITLE
Is there any solution for re-layout when images loaded?

### ISSUE THREAD

**Issue by shisoft** [kudago/waterfall#5]
I used to use a fixed height for each item, but still cannot fit my design, the height changes after waterfall took effect makes it looked bad. I am just wondering is there any possibility to observe height changes or image loaded for each item?

**Comment by GGGTek** [comment]
Is there a sample on how to use the code you have above in regard to "passing img width/height as data-attributes", I know my imgs width and height ahead of time, but I don't know how to pass them to waterfall?  Thanks.
